name: TypeScript

on:
  push: ~
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.30.0

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test

      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            cjs/
            esm/
            .npmrc
            package.json
            pnpm-lock.yaml
            LICENCE.md
            README.md

  publish:
    runs-on: ubuntu-20.04
    needs:
      - build
    if: ${{ github.event_name == 'release' }}
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dist

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.30.0

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: pnpm

      - name: Version
        run: pnpm version ${TAG_NAME:1}
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}

      - name: Publish
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
